# Site settings
title: James Curtin's Personal Site
email: jameswcurtin@alumni.harvard.edu
description: >-
  Hi, my name is James Curtin, and this is my personal site.
  Please read on for more information about my work experience,
  educational background, and photography portfolio
# baseurl: "/"
author: James W. Curtin
url: "https://www.jamescurtin.com"
twitter:
  username: james_curtin
facebook:
  admins: 10209490154282806
github: [metadata]

logo: /includes/img/logo.png
social:
  name: James Curtin
  links:
    - https://twitter.com/james_curtin
    - https://www.facebook.com/jameswcurtin
    - https://www.linkedin.com/in/jameswcurtin/
    - https://github.com/jamescurtin
    - https://keybase.io/jameswcurtin

  webmaster_verifications:
    google: googlecdb7543c95ed9495.html

# Build settings
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

whitelist:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag