baseURL = "https://jamescurtin.com/"
languageCode = "en-us"
title = "James W. Curtin"
theme = ["hello-friend", "resume"]
googleAnalytics = "UA-57664313-1"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

canonifyURLs    = true
enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
Copyright = '<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">CC BY-NC-ND 4.0</a>'

[author]
  name = "James Curtin"

[menu]
  # [[menu.main]]
  #   identifier = "resume"
  #   name       = "Resume"
  #   url        = "/resume"
  # [[menu.main]]
  #   identifier = "portfolio"
  #   name = "Portfolio"
  #   url = "/portfolio"
  # [[menu.main]]
  #   identifier = "portraits"
  #   name = "Portraits"
  #   parent = "portfolio"
  #   url = "/portraits"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  homeTitle = "James W. Curtin, Jr."
  homeSubtitle = "Software Engineering Manager"
  gitUrl = "https://github.com/jamescurtin/jamescurtin.github.io/commit/"

  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [params.logo]
    logoText     = "jamescurtin/"
    logoHomeLink = "/"
    logoCursorColor    = "#2b7bbe"

  [[params.social]]
    name = "github"
    icon = "fab fa-github"
    url  = "https://github.com/jamescurtin"
  [[params.social]]
    name = "keybase"
    icon = "fab fa-keybase"
    url  = "https://keybase.io/jameswcurtin"
  [[params.social]]
    name = "linkedin"
    icon = "fab fa-linkedin-in"
    url  = "https://www.linkedin.com/in/jameswcurtin"
  [[params.social]]
    name = "email"
    icon = "far fa-envelope"
    url  = "mailto:james@jamescurtin.com"

  [params.portrait]
    path     = "assets/images/avatar.png"
    alt      = "Portrait"

  [params.resume]
    description = "James Curtin's Resume"
    primaryColor = "#2B7BBE"
    textPrimaryColor = "#292929"

    [params.resume.profile]
      enable = true
      name = "James W. Curtin"
      tagline = "Software Engineering Manager"
      avatar = "avatar.png"

    [params.resume.summary]
        enable = false
        text = ""

    [params.resume.contact]
      enable = true
      location = "Boston"
      [[params.resume.contact.list]]
        icon = "fas fa-mobile"
        url = "tel:+15089421412"
        text = "Call Me"
      [[params.resume.contact.list]]
        icon = "fas fa-envelope"
        url = "mailto:james@jamescurtin.com"
        text = "Email Me"
      [[params.resume.contact.list]]
        icon = "fas fa-globe"
        url = "https://jamescurtin.com"
        text = "jamescurtin.com"


    [params.resume.skills]
      enable = true
      [[params.resume.skills.list]]
        title = "Technical"
      [[params.resume.skills.list.items]]
        details = "Python"
      [[params.resume.skills.list.items]]
        details = "Event driven systems (Kafka, Avro)"
      [[params.resume.skills.list.items]]
        details = "Docker"
      [[params.resume.skills.list.items]]
        details = "Kubernetes, Helm"
      [[params.resume.skills.list.items]]
        details = "CI/CD"
      [[params.resume.skills.list.items]]
        details = "Git"
      [[params.resume.skills.list.items]]
        details = "Python Compilation and Linking (Manylinux)"

    [params.resume.education]
      enable = true
      [[params.resume.education.list]]
        degree = "AB in Government, Computer Science"
        university = "Harvard College"

    [params.resume.awards]
      enable = false
      [[params.resume.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"

    [params.resume.languages]
      enable = false
      [[params.resume.languages.list]]
        name = "English"
        level = "Native"

    [params.resume.interests]
      enable = true
      [[params.resume.interests.list]]
      name = "Photography"
      [[params.resume.interests.list]]
      name = "Scouting (Eagle Scout)"
      [[params.resume.interests.list]]
      name = "Falconry (Licensed falconer)"


    [params.resume.experience]
      enable = true

      [[params.resume.experience.list]]
        title = "Sr. Engineering Manager, Developer Platforms"
        dates = "2020 - Present"
        company = "Wayfair LLC"
        details = "Lead and grow developer infrastructure teams, tasked with the mission of increasing the efficiency and velocity of Wayfair's product engineers."

      [[params.resume.experience.list]]
        title = "Sr. Engineer -> Engineering Manager, Python Platforms"
        dates = "2020"
        company = "Wayfair LLC"
        details = "Transferred to the Python Platform team as a Sr. Engineer, then moved laterally to Manager"

      [[params.resume.experience.list]]
        title = "Manager, Wayfair Professional (B2B)"
        dates = "2017 - 2019"
        company = "Wayfair LLC"

      [[params.resume.experience.list]]
        title = "Performance Marketing"
        dates = "Jun 2016 - Jul 2017"
        company = "Everquote Inc."

      [[params.resume.experience.list]]
        title = "Associate"
        dates = "May 2014 - Aug 2014"
        company = "The White House"

    [params.resume.projects]
      enable = true

      [[params.resume.projects.list]]
        title = "cookiecutter-flask"
        meta = "Open Source"
        tagline = "Primary maintainer of Flask template that provides out-of-the box support for creating new web applications (~3k stars on Github)."

      [[params.resume.projects.list]]
        title = "sonarscanner-buildkite-plugin"
        meta = "Open Source"
        tagline = "Developed plugin that enables developers to report back to Sonarqube as part of a Buildkite CI pipeline."


    [params.resume.information]
      enable = false

      [[params.resume.information.list]]
        title = "Papers"
      [[params.resume.information.list.items]]
        details = "2018 · Lorem Ipsum"
